#pragma once
static const char page[]=R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AIEdge setup</title>
<style>body{font:16px system-ui;background:#f3f7f8;color:#172a36;margin:24px auto;padding:16px;max-width:520px}main{background:white;padding:24px;border-radius:16px}input,select,button{box-sizing:border-box;width:100%;font:inherit;padding:12px;margin:8px 0 16px;border:1px solid #a5bac5;border-radius:8px}button{background:#006e69;color:white;cursor:pointer}button.secondary{background:white;color:#006e69}button:disabled{opacity:.5;cursor:wait}input[type=checkbox]{width:auto;margin-right:8px}.hint{font-size:.9rem;color:#4c626e}progress{width:100%}[hidden]{display:none!important}</style></head>
<body><main><h1>AIEdge</h1><p>Choose your home Wi-Fi to download and install AIEdge.</p>
<form id="wifi"><fieldset id="fields" style="border:0;padding:0;margin:0"><label for="networks">Wi-Fi network</label><select id="networks"><option value="">Select a network</option><option value="manual">Hidden network / enter manually</option></select>
<button class="secondary" id="scan" type="button">Rescan networks</button><p id="scan-status" class="hint" role="status">Looking for nearby 2.4 GHz networks…</p>
<div id="manual" hidden><label for="ssid">Wi-Fi name</label><input id="ssid" maxlength="31" autocomplete="off" autocapitalize="none" spellcheck="false"></div>
<label for="password">Password</label><input id="password" type="password" maxlength="63" autocomplete="new-password" autocapitalize="none" spellcheck="false"><label><input id="show" type="checkbox">Show password</label>
<button id="go" type="submit">Connect and install</button></fieldset></form>
<p id="state" role="status">Checking device…</p><progress id="progress" max="100" value="0" aria-label="Package download"></progress>
<p class="hint">Keep AIEdge powered during installation. Afterwards, reconnect your phone to home Wi-Fi and open <a href="http://aiedge.local">aiedge.local</a>.</p></main>
<script>
const $=id=>document.getElementById(id), state=$('state'), fields=$('fields'), networks=$('networks'), password=$('password');
let busy=true, scanning=false, started=false, choices=[];
function controls(){fields.disabled=busy;$('scan').disabled=busy||scanning;$('go').disabled=busy||scanning;}
function selection(){const manual=networks.value==='manual';$('manual').hidden=!manual;$('ssid').required=manual;const ap=choices[Number(networks.value)];const open=!manual&&networks.value!==''&&ap&&ap.open;password.disabled=!!open;password.required=!open;password.minLength=open?0:8;if(open)password.value='';}
$('show').onchange=()=>{password.type=$('show').checked?'text':'password';};networks.onchange=selection;
async function scan(){if(busy||scanning)return;scanning=true;controls();$('scan-status').textContent='Scanning nearby 2.4 GHz networks…';try{const r=await fetch('/scan',{method:'POST'});if(!r.ok)throw Error(await r.text());}catch(e){scanning=false;controls();$('scan-status').textContent='Could not scan. Try Rescan or enter the network manually.';}}
$('scan').onclick=scan;
function renderNetworks(items){const previous=choices[Number(networks.value)]?.ssid, manual=networks.value==='manual';const seen=new Set();choices=items.sort((a,b)=>b.rssi-a.rssi).filter(n=>{if(seen.has(n.ssid))return false;seen.add(n.ssid);return true;});networks.replaceChildren(new Option('Select a network',''));
choices.forEach((n,i)=>{const strength=n.rssi>=-60?'Strong':n.rssi>=-75?'Good':'Weak';const supported=n.supported&&new TextEncoder().encode(n.ssid).length<=31&&!/["\r\n]/.test(n.ssid);const option=new Option(`${n.ssid} · ${strength}${n.open?' · Open':''}${supported?'':' · Not supported'}`,String(i));option.disabled=!supported;networks.add(option);if(n.ssid===previous&&supported)networks.value=String(i);});networks.add(new Option('Hidden network / enter manually','manual'));if(manual)networks.value='manual';selection();$('scan-status').textContent=choices.length?`${choices.length} networks found. 2.4 GHz Wi-Fi only.`:'No networks found. Rescan or enter the name manually.';}
$('wifi').onsubmit=async e=>{e.preventDefault();if(busy||scanning)return;const manual=networks.value==='manual';const ap=choices[Number(networks.value)];const name=manual?$('ssid').value:(networks.value!==''&&ap?ap.ssid:'');if(!name){state.textContent='Choose a Wi-Fi network first.';return;}if(new TextEncoder().encode(name).length>31||/["\r\n]/.test(name)||/["\r\n]/.test(password.value)){state.textContent='This build supports names up to 31 bytes, without quotes or line breaks.';return;}busy=true;controls();state.textContent='Connecting to Wi-Fi…';try{const r=await fetch('/wifi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:name,password:password.disabled?'':password.value})});if(!r.ok){state.textContent=await r.text();busy=false;controls();}}catch(e){state.textContent='Connection interrupted. Checking device status…';}};
async function poll(){try{const r=await fetch('/status',{cache:'no-store'});if(!r.ok)throw Error();const s=await r.json();busy=s.phase>0;state.textContent=s.message;$('progress').value=s.progress;controls();if(!started){started=true;if(!busy)await scan();}if(scanning){const n=await fetch('/networks',{cache:'no-store'});if(!n.ok)throw Error();const result=await n.json();if(result.state!==1){scanning=false;controls();if(result.state===2)renderNetworks(result.networks);else $('scan-status').textContent='Scan failed. Rescan or enter the network manually.';}}}catch(e){state.textContent='Device not responding. Stay connected to AIEdge-Setup during setup.';}finally{setTimeout(poll,2000);}}
controls();poll();
</script></body></html>)HTML";
