"""Generate the compiled two-model role contract from explicit model artifacts."""
import argparse,hashlib,json
from pathlib import Path

def generate(main, secondary):
    roles=[]
    for name,path,asset,indices in [('Main',main,'model/polar-main-int8.tflite',list(range(5))),('Secondary',secondary,'model/polar-int8.tflite',[5])]:
        raw=Path(path).read_bytes()
        if not raw: raise ValueError('Empty model')
        roles.append(dict(role=name,asset=asset,bytes=len(raw),sha256=hashlib.sha256(raw).hexdigest(),dial_indices=indices))
    contract=dict(format='aiedge-polar-roles-v1',roles=roles)
    canonical=json.dumps(contract,sort_keys=True,separators=(',',':')).encode('utf-8')
    identity=hashlib.sha256(canonical).hexdigest()
    lines=['// Generated by tools/bundle-tests/export_model_roles.py; do not edit.', '#pragma once','#include <cstddef>','#include <cstdint>','namespace polar {','enum class ModelRole { Main, Secondary };','struct ModelSpec { const char* asset; size_t bytes; const char* hex; uint8_t digest[32]; };',f'static const char routedReaderIdentity[]="{identity}";']
    for r in roles:
        digest=','.join('0x'+r['sha256'][i:i+2] for i in range(0,64,2))
        lines.append('static const ModelSpec '+r['role'].lower()+'Model={"'+r['asset']+'",'+str(r['bytes'])+',"'+r['sha256']+'",{'+digest+'}};')
    lines+=['inline const ModelSpec* modelSpec(ModelRole role) {',' switch(role) { case ModelRole::Main:return &mainModel; case ModelRole::Secondary:return &secondaryModel; }',' return nullptr;','}','}']
    return ('\n'.join(lines)+'\n').encode('utf-8'),canonical+b'\n'

def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--main-model',required=True,type=Path);p.add_argument('--secondary-model',required=True,type=Path)
    p.add_argument('--output',required=True,type=Path);p.add_argument('--verify',action='store_true');a=p.parse_args()
    header,manifest=generate(a.main_model,a.secondary_model)
    for name,data in [('PolarModelRoles.h',header),('PolarModelRoles.json',manifest)]:
        target=a.output/name
        if a.verify:
            if target.read_bytes()!=data: raise ValueError('Role contract differs: '+name)
        else:
            with target.open('xb') as f:f.write(data)
    print('Role contract verified' if a.verify else 'Role contract generated')
if __name__=='__main__': main()
