const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'archive.js'),'utf8');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(){
 const elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,{checked:false,value:'',hidden:false,disabled:false,textContent:'',dataset:{}});return elements.get(id);};
 let state={state:'disabled',config:{enabled:false,directory:''},revision:'first',copied_events:0,pending_events:2,error:null,in_progress:false},failure=null;
 const calls=[],listeners={},location={hash:'#setup/data'},window={addEventListener:(name,fn)=>listeners[name]=fn};
 const fetch=async(url,options={})=>{
  calls.push({url,options});if(url==='api/setup')return {ok:true,json:async()=>({token:'fixture'})};
  if(failure)return {ok:false,json:async()=>({error:failure})};
  if(options.method==='POST'){const request=JSON.parse(options.body);if(request.revision!==state.revision)return {ok:false,json:async()=>({error:'archive_config_changed'})};if(request.action==='save')state={...state,config:request.config,revision:'saved'};}
  return {ok:true,json:async()=>JSON.parse(JSON.stringify(state))};
 };
 vm.runInContext(source,vm.createContext({window,document:{getElementById:get,hidden:false},location,fetch,AbortSignal,setInterval:()=>1,clearInterval(){}}));
 return {get,calls,window,location,listeners,setState(value){state={...state,...value};},fail(value){failure=value;}};
}
test('default local storage has no POST or network-share probe',async()=>{const f=fixture();await tick();assert.equal(f.get('archive-enabled').checked,false);assert.equal(f.get('archive-options').hidden,true);assert.equal(f.calls.filter(c=>c.options.method==='POST').length,0);assert.match(f.get('archive-status').textContent,/Home Assistant/);});
test('editing archive choices waits for Next instead of starting a copy',async()=>{const f=fixture();await tick();f.get('archive-enabled').checked=true;f.get('archive-enabled').onchange();f.get('archive-directory').value='/media/meter';f.get('archive-directory').oninput();assert.equal(f.get('archive-options').hidden,false);assert.equal(f.calls.filter(c=>c.options.method==='POST').length,0);assert.equal(await f.window.AIEdgeArchive.save(),true);const body=JSON.parse(f.calls.at(-1).options.body);assert.deepEqual(body.config,{enabled:true,directory:'/media/meter'});});
test('unchanged Next does not rewrite the archive ledger',async()=>{const f=fixture();await tick();assert.equal(await f.window.AIEdgeArchive.save(),true);assert.equal(f.calls.filter(c=>c.options.method==='POST').length,0);});
test('polling retains edits and their original revision when another session changes choices',async()=>{const f=fixture();await tick();f.get('archive-enabled').checked=true;f.get('archive-enabled').onchange();f.get('archive-directory').value='/media/mine';f.get('archive-directory').oninput();f.setState({config:{enabled:true,directory:'/media/theirs'},revision:'other'});await f.window.AIEdgeArchive.load();assert.equal(f.get('archive-directory').value,'/media/mine');assert.equal(await f.window.AIEdgeArchive.save(),false);const body=JSON.parse(f.calls.at(-1).options.body);assert.equal(body.revision,'first');assert.match(f.get('archive-status').textContent,/another session/);});
test('reload after conflict uses saved choices explicitly',async()=>{const f=fixture();await tick();f.setState({config:{enabled:true,directory:'/media/other'},revision:'other'});await f.window.AIEdgeArchive.load(true);assert.equal(f.get('archive-directory').value,'/media/other');assert.equal(f.get('archive-enabled').checked,true);});
test('failure messages are bounded and retry stays disabled while editing',async()=>{const f=fixture();await tick();f.setState({state:'retrying',config:{enabled:true,directory:'/media/test'},error:'archive_timeout'});await f.window.AIEdgeArchive.load();assert.match(f.get('archive-status').textContent,/did not respond/);assert.equal(f.get('archive-retry').hidden,false);f.get('archive-directory').oninput();assert.equal(f.get('archive-retry').disabled,true);});
test('failed initial load cannot save a default over stored choices',async()=>{const f=fixture();await tick();f.fail('archive_unavailable');f.location.hash='#settings';f.listeners.hashchange();await tick();assert.equal(f.get('settings-archive').textContent,'Unavailable');assert.equal(f.get('archive-reload').hidden,false);});
test('status polling does not erase a save error before the user corrects it',async()=>{const f=fixture();await tick();f.get('archive-enabled').checked=true;f.get('archive-enabled').onchange();f.fail('archive_choices_invalid');assert.equal(await f.window.AIEdgeArchive.save(),false);const message=f.get('archive-status').textContent;f.fail(null);await f.window.AIEdgeArchive.load();assert.equal(f.get('archive-status').textContent,message);f.get('archive-directory').value='/media/corrected';f.get('archive-directory').oninput();assert.equal(f.get('archive-status').textContent,'Unsaved archive choices.');});
